<?php
function header_collector_menu() {
  $menu['headercollector'] = array(
                                    'title' => 'Collected Headers',
                                    'description' => 'handy',
                                    'page callback' => 'header_collector_page',
                                    'access arguments' => array('View collected headers'),
                                   );
  return $menu;
}

function header_collector_page() {
  $headers = array(
                   array('field' => 'ua', 'data' => 'User Agent', 'sort' => 'asc'),
                  );
  $result = pager_query("SELECT * FROM {visitor}". tablesort_sql($headers));
  while ($row = db_fetch_object($result)) {
    $http = header_collector_get_list($row->vid);
    $rows[] = array($row->ua, theme('item_list', $http));
  }
  $output = theme('table', $headers, $rows);
  $output .= theme('pager', null, 100, 0);
  return  $output;
}

function header_collector_get_list($vid) {
  $result = db_query("SELECT * FROM {visitor_headers} WHERE vid=%d", $vid);
  while ($row = db_fetch_object($result)) {
    $headers[] = t('!name = !value', array('!name' => $row->header_name, '!value' => $row->header_value));
  }
  return $headers;
}