<?php
function header_collector_menu() {
  $menu['headercollector'] = array(
                                    'title' => 'Collected Headers',
                                    'description' => 'handy',
                                    'page callback' => 'header_collector_page',
                                    'access arguments' => array('View collected headers'),
                                   );
  $menu['headercollector/edit'] = array('page callback' => 'drupal_get_form', 'page_arguments' => array('header_collector_edit'));
  return $menu;
}

function header_collector_page() {
  $headers = array(
                   array('field' => 'visited', 'data' => 'Time of visit', 'sort' => 'desc'),
                   array('field' => 'ua', 'data' => 'User Agent'),
                     'MDL',
                   'http headers',
                   'notes',
                  );
  $result = pager_query("SELECT * FROM {visitor}". tablesort_sql($headers));
  while ($row = db_fetch_object($result)) {
    $http = header_collector_get_list($row->vid);
    $rows[] = array(format_date($row->visited), $row->ua, $row->mdl_content_type, theme('item_list', $http));
  }
  $output = theme('table', $headers, $rows);
  $output .= theme('pager', null, 100, 0);
  return  $output;
}

function header_collector_get_list($vid) {
  $result = db_query("SELECT * FROM {visitor_headers} WHERE vid=%d", $vid);
  while ($row = db_fetch_object($result)) {
    $headers[] = t('!name = !value', array('!name' => $row->header_name, '!value' => $row->header_value));
  }
  return $headers;
}

function header_collector_edit($vid) {
  
}